### PR TITLE
Update thrift to v0.11.0

### PR DESCRIPTION
**Pull request by pkotikal**
Updating thrift to v0.11.0 for Python3 support

### CODE REVIEW

**Comment by pkotikal** [comment]
> This is fine by me. Did you make sure that the bmv2 docker image could still build properly and run the tests?

I was able to build the bmv2 docker image. How do I run the tests - where do I find the testsuite?

**Comment by cc10512** [comment]
`make check`

**Comment by antoninbas** [comment]
yes you should do what the travis file does basically: https://github.com/p4lang/behavioral-model/blob/master/.travis.yml#L30
and run `make check` inside the docker container

**Comment by pkotikal** [comment]
Thanks @cc10512, @antoninbas, all the tests pass as well. I'll verify the compilers tests as well and merge the PR.

**Comment by antoninbas** [comment]
Sounds good.

**Pull request merged**
