### PR TITLE
Grpc v1.17.2

### PR DESCRIPTION
**Pull request by pkotikal**
@jnfoster, does this change impact the tutorials repo?

### CODE REVIEW

**Comment by pkotikal** [comment]
> LGTM, you will need to update the stable branch as well after that as it is the one used to build downstream Docker images IIRC

Will do. Thanks.

**Comment by jnfoster** [comment]
LGTM. We can fix up the tutorials as needed before the next release, or pin to an old version.

**Comment by pkotikal** [comment]
@antoninbas, I'm seeing gtest failure with v3.6.1.
`5095: Test command: /mnt/build/p4c/test/gtestp4c
5095: Test timeout computed to be: 9.99988e+06
5095: terminate called after throwing an instance of 'std::system_error'
5095:   what():  Unknown error -1
1/1 Test #5095: gtestp4c .........................***Exception: Other  1.40 sec`

I tried moving to v3.9.2 and I get the tests to run but still see few failures -
`5095: [  FAILED  ] P4RuntimePkgInfo.GeneralCase
5095: [  FAILED  ] P4RuntimePkgInfo.OverrideArch
5095: [  FAILED  ] P4RuntimeDataTypeSpec.Tuple
5095: [  FAILED  ] FromJSONTest.load_ir_from_json` 

I'm debugging them, will update when I find something.
So far, for `P4RuntimePkgInfo.GeneralCase`, https://github.com/p4lang/p4c/blob/master/control-plane/p4RuntimeSerializer.cpp#L1204 accesses GetDescriptor() from pkgInfo. In older versions of protobuf, it was accessed from https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/message.h#L327. 
But, in v3.9.2 it's through the PkgInfo class in the generated p4info.pb.h file -
`  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }`, and it eventually crashes at -
` ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_p4_2fconfig_2fv1_2fp4info_2eproto);
    return ::descriptor_table_p4_2fconfig_2fv1_2fp4info_2eproto.file_level_metadata[kIndexInFileMessages];
  }`

**Comment by antoninbas** [comment]
I don't think we should move to Protobuf 3.9.2 if we agreed to use 3.6.1. The officially supported Protobuf version for gRPC 1.17.2 is Protobuf 3.6.1: https://github.com/grpc/grpc/tree/v1.17.2/third_party

You should be able to debug the `std::system_error` exception.

**Comment by cc10512** [comment]
The `Unknown error: -1`? Any hints on where to look?

**Comment by pkotikal** [comment]
> I don't think we should move to Protobuf 3.9.2 if we agreed to use 3.6.1. The officially supported Protobuf version for gRPC 1.17.2 is Protobuf 3.6.1: https://github.com/grpc/grpc/tree/v1.17.2/third_party
> 
> You should be able to debug the `std::system_error` exception.

Here's the stack trace if it helps -
`terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1

Thread 1 "gtestp4c" received signal SIGABRT, Aborted.
0x00007ffff61e0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff61e0428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff61e202a in __GI_abort () at abort.c:89
#2  0x00007ffff6b2f242 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b3ae86 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b3aed1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6b3b105 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6b31d58 in std::__throw_system_error(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x0000000003975806 in std::call_once<void (&)()> (__once=...,
    __f=@0x3944cbc: {void (void)} 0x3944cbc <protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::AddDescriptorsImpl()>) at /usr/include/c++/6/mutex:622
#8  0x000000000396d394 in google::protobuf::internal::call_once<std::once_flag&, void (&)()> (args#0=...,
    args#1=@0x3944cbc: {void (void)} 0x3944cbc <protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::AddDescriptorsImpl()>)
    at /usr/local/include/google/protobuf/stubs/once.h:91
#9  0x0000000003944d03 in protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::AddDescriptors () at /mnt/build/p4c/control-plane/p4/config/v1/p4info.pb.cc:1014
#10 0x000000000396c537 in protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::StaticDescriptorInitializer::StaticDescriptorInitializer (
    this=0x64aab50 <protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::static_descriptor_initializer>)
    at /mnt/build/p4c/control-plane/p4/config/v1/p4info.pb.cc:1019
#11 0x00000000039679c3 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at /mnt/build/p4c/control-plane/p4/config/v1/p4info.pb.cc:1021
#12 0x00000000039679d9 in _GLOBAL__sub_I__ZN2p46config2v125_P4Info_default_instance_E () at /mnt/build/p4c/control-plane/p4/config/v1/p4info.pb.cc:10502
#13 0x00000000042b801d in __libc_csu_init ()
#14 0x00007ffff61cb7bf in __libc_start_main (main=0x2bdf2be <main(int, char**)>, argc=2, argv=0x7fffffffd8f8, init=0x42b7fd0 <__libc_csu_init>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd8e8) at ../csu/libc-start.c:247
#15 0x00000000028938f9 in _start ()`

**Comment by antoninbas** [comment]
You can catch the exception in gdb with `catch throw` and see where it originates from.

This kind of error is concerning IMO. You want to make sure that you are consistently using the same version of the Protobuf / gRPC libraries.

**Comment by pkotikal** [comment]
> You can catch the exception in gdb with `catch throw` and see where it originates from.
> 
> This kind of error is concerning IMO. You want to make sure that you are consistently using the same version of the Protobuf / gRPC libraries.

`Thread 1 "gtestp4c" hit Catchpoint 1 (exception thrown), 0x00007ffff6b3b0ce in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff6b3b0ce in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff6b31d58 in std::__throw_system_error(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000003975806 in std::call_once<void (&)()> (__once=...,
    __f=@0x3944cbc: {void (void)} 0x3944cbc <protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::AddDescriptorsImpl()>) at /usr/include/c++/6/mutex:622
#3  0x000000000396d394 in google::protobuf::internal::call_once<std::once_flag&, void (&)()> (args#0=...,
    args#1=@0x3944cbc: {void (void)} 0x3944cbc <protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::AddDescriptorsImpl()>)
    at /usr/local/include/google/protobuf/stubs/once.h:91`

The versions seem to be correct -
`Name: gRPC++
Description: C++ wrapper for gRPC
Version: 1.17.1`
`Name: gRPC
Description: high performance general RPC framework
Version: 7.0.0`
`Name: Protocol Buffers
Description: Google's Data Interchange Format
Version: 3.6.1`

**Comment by pkotikal** [comment]
> You can catch the exception in gdb with `catch throw` and see where it originates from.
> 
> This kind of error is concerning IMO. You want to make sure that you are consistently using the same version of the Protobuf / gRPC libraries.

Something seems off. Let me rebuild from scratch -
`p4lang/third-party   grpc-v1.17.2        891d32e88275        6 months ago        283MB
docker run p4lang/third-party:grpc-v1.17.2 image
root@4efc650c7965:/mnt# cat /usr/local/lib/pkgconfig/grpc++.pc
Name: gRPC++
Description: C++ wrapper for gRPC
Version: 1.17.1`

**Comment by pkotikal** [comment]
@antoninbas, rebuilt from this (grpc-v1.17.2) branch. Still see the same -
`root@11251da071f8:/mnt# cat /usr/local/lib/pkgconfig/grpc++.pc
Name: gRPC++
Description: C++ wrapper for gRPC
Version: 1.17.1`
And, grpc top commit is -
`commit c7cc34e2d76afe67528ac5b20c5ccbe0692757e8
Merge: eedcd2a d3d8a37
Author: Nicolas Noble <nicolasnoble@users.noreply.github.com>
Date:   Fri Dec 14 13:31:40 2018 -0800
    Merge pull request #17446 from moriarty/cherry-pick-fix-bazel-0.20
    Cherry pick fix bazel 0.20`

**Comment by antoninbas** [comment]
It's this: https://stackoverflow.com/questions/51584960/stdcall-once-throws-stdsystem-error-unknown-error-1

Replacing `target_link_libraries (controlplane ${PROTOBUF_LIBRARY})` with `target_link_libraries (controlplane PUBLIC ${PROTOBUF_LIBRARY} pthread)` in `p4c/control-plane/CMakeLists.txt` fixed the issue for me. You may want to look into it further though (is it the best place to fix this - probably yes -, is the `PUBLIC` keyword required - probably no -).

**Comment by pkotikal** [comment]
Thanks @antoninbas

**Comment by pkotikal** [comment]
@antoninbas, I updated this change in `stable` branch as well. Could you please trigger the dockerhub builds for third-party and the downstream jobs in p4lang registry. I don't have permissions to trigger the jobs.

**Comment by antoninbas** [comment]
As far as I can tell it seems to have triggered automatically.

**Comment by pkotikal** [comment]
> As far as I can tell it seems to have triggered automatically.

Ok, I'm not seeing the build in progress. Will check back later, for the updated tag with the last built timestamp.

**Pull request merged**
